web: php artisan config:clear && php artisan config:cache && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}
worker: while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done
